data:extend({
	{
		type = "bool-setting",
		name = "rd-fuelmix-display-out-of-fuel",
		setting_type = "startup",
		default_value = true,
		order = "aa",
	},
	{
		type = "bool-setting",
		name = "rd-fuelmix-separate-research",
		setting_type = "startup",
		default_value = true,
		order = "aba",
	},
	{
		type = "bool-setting",
		name = "rd-fuelmix-solid-enable",
		setting_type = "startup",
		default_value = true,
		order = "ba",
	},
	{
		type = "int-setting",
		name = "rd-fuelmix-solid-amount",
		setting_type = "startup",
		default_value = 1,
		order = "bb",
	},
	{
		type = "double-setting",
		name = "rd-fuelmix-solid-fuelrequired",
		setting_type = "startup",
		default_value = 10,
		order = "bc",
	},
	{
		type = "double-setting",
		name = "rd-fuelmix-solid-fuelvalue",
		setting_type = "startup",
		default_value = 10,
		order = "bd",
	},
	{
		type = "double-setting",
		name = "rd-fuelmix-solid-acceleration",
		setting_type = "startup",
		default_value = 1.0,
		order = "be",
	},
	{
		type = "double-setting",
		name = "rd-fuelmix-solid-topspeed",
		setting_type = "startup",
		default_value = 1.0,
		order = "bf",
	},
	{
		type = "bool-setting",
		name = "rd-fuelmix-fluid-enable",
		setting_type = "startup",
		default_value = true,
		order = "ca",
	},
	{
		type = "int-setting",
		name = "rd-fuelmix-fluid-amount",
		setting_type = "startup",
		default_value = 5,
		order = "cb",
	},
	{
		type = "double-setting",
		name = "rd-fuelmix-fluid-fuelrequired",
		setting_type = "startup",
		default_value = 2,
		order = "cc",
	},
	{
		type = "double-setting",
		name = "rd-fuelmix-fluid-fuelvalue",
		setting_type = "startup",
		default_value = 2,
		order = "cd",
	},
})
