data:extend({
	{
		type = "bool-setting",
		name = "rd-warehousing-override-slots",
		setting_type = "startup",
		default_value = true,
		order = "a-a",
	},
	{
		type = "int-setting",
		name = "rd-warehousing-count-warehouse-slots",
		setting_type = "startup",
		default_value = 1800,
		minimum_value = 1,
		maximum_value = 65535,
		order = "a-b-a",
	},
	{
		type = "int-setting",
		name = "rd-warehousing-count-storage-warehouse-slots",
		setting_type = "startup",
		default_value = 2000,
		minimum_value = 1,
		maximum_value = 65535,
		order = "a-b-b",
	},
	{
		type = "int-setting",
		name = "rd-warehousing-count-storehouse-slots",
		setting_type = "startup",
		default_value = 450,
		minimum_value = 1,
		maximum_value = 65535,
		order = "a-b-c",
	},
	{
		type = "int-setting",
		name = "rd-warehousing-count-storage-storehouse-slots",
		setting_type = "startup",
		default_value = 500,
		minimum_value = 1,
		maximum_value = 65535,
		order = "a-b-d",
	},
	{
		type = "bool-setting",
		name = "rd-warehousing-compat-pyanodons",
		setting_type = "startup",
		default_value = true,
		order = "b-a",
	},
})
